### ISSUE TITLE
Disassembler Crashes When Code is Loaded on an Odd Byte Boundary

### ISSUE THREAD

**Issue by AlexanderAdelAU** [endlos99/xdt99#21]
LiClipse produces the following error when running xda99 against the file at this link: [https://www.dropbox.com/s/zk87ceivpet63pd/sieve.rar?dl=1](url)

I am not sure if the error lies within the disassembler or the PyDev implementation on LiClipse however I thought that I would flag it as a possible issue.   I have walked though the code manually (not run native) and it appears to be sound.

`Traceback (most recent call last):
  File "C:\Development-W7DEV\LiClipse Workspace\xda99\src\xda99.py", line 909, in <module>
    status = main()
  File "C:\Development-W7DEV\LiClipse Workspace\xda99\src\xda99.py", line 872, in main
    program = Program(binary, addr, symbols=symbols)
  File "C:\Development-W7DEV\LiClipse Workspace\xda99\src\xda99.py", line 580, in __init__
    self.code = [Unknown(addr + i, ordw(binary[i:i + 2]))  # listing of entries
  File "C:\Development-W7DEV\LiClipse Workspace\xda99\src\xda99.py", line 580, in <listcomp>
    self.code = [Unknown(addr + i, ordw(binary[i:i + 2]))  # listing of entries
  File "C:\Development-W7DEV\LiClipse Workspace\xda99\src\xda99.py", line 34, in ordw
    return (word[0] << 8) | word[1]
IndexError: index out of range
`

**Comment by endlos99** [comment]
OK, this seems like another bug.

Could you tell me how you invoked `xda99`, i.e., what the arguments were?

**Comment by AlexanderAdelAU** [comment]
Yes,  sieve.bin -a 0100 -f 0100

**Comment by AlexanderAdelAU** [comment]
For your info.  I discovered the source of the problem.  The crash dump is caused if any of executable source code lies on an odd boundary.    

For example

	cc1: BYTE 49,48,0  <--- ODD NUMBER OF BYTES
        ENT main
	ENT flags
	EXT printf
	EVEN   <---  ADDING THIS MAKES SURE FOLLOWING MODULE ARE LOADED ON AN EVEN BOUNDARY
	END`

So in summary, you probably don't need to fix you disassembler if you trust the users will load properly aligned code, however I thought I would pass this on in case you want to perform any additional checks in your python code.

By the way, I have found your software exceedingly useful - so thank you very much.

**Comment by endlos99** [comment]
I think it's related to that, but `xda99` will **always** disassemble at even addresses.  If code is located at odd addresses, then `xda99` will just return nonsense.

The actual issue is that your file has odd length, but `xda99` reads words.  The simplest fix would be to pad odd-length code with a zero byte, but I hope to handle this more gracefully when I got time.
